<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>About</title>
</head>
<body>
    <div class="container">
            <div class="navbar" >
                <nav class="navigation">
                <br>
                <a class="main-icon" href="home.phtml">Anmol</a>
                <a class="nav-icon" href="home.phtml">Home</a>
                <a class="nav-icon" href="about.phtml" style="background-color: gray;  border-radius: 12px 12px 0px 0px;">About</a>
                <a class="nav-icon" href="projects.php">Projects</a>
                <a class="nav-icon" href="skills.phtml">Skills</a>
                <a class="nav-icon" href="contact.phtml">Contact</a>
                <a class="nav-icon" href="profile.phtml">Hello, </a>
                <a class="logout" href="logout.php">Logout</a>
                <br>
                </nav>
        </div>
        
    </div>
</body>
</html>