<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Admin Login</title>
</head>
<body>
    <div class="conainer">
        <div class="navbar" >
             <nav class="navigation">
                <br>
                <a class="main-icon" href="admin.phtml">Anmol</a>
                <a class="nav-icon-admin" href="admin.phtml" style="background-color: gray;  border-radius: 12px 12px 0px 0px;">Home</a>
                <a class="nav-icon-admin" href="cutumers.phtml">Customers</a>
                <a class="nav-icon-admin" href="products-admin.phtml">Products</a>
                <a class="logout" href="logout-admin.php">Logout</a>
                <br>
            </nav>
        </div>
    </div>
</body>
</html>