<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Login</title>
</head>
<body>
    <div>
        <div class="container">
                <div class="navbar" >
                    <nav class="navigation">
                        <br>
                        <a class="main-icon" href="home.phtml">Anmol</a>
                        <br>
                    </nav>
                </div>
                <div class="login-div">
                        <h1 style ="padding-left: 20px;">Login</h1>
                        <center>
                        <form action="login.php" method="post">    
                            <input class="namebox" type="text" name="username" placeholder="Enter Your User Name" require>
                            <br>
                            <br>
                            <br>
                            <input class="namebox" type="password" name="pass" placeholder="Enter Your Password" require>
                            <br>
                            <br>
                            <br>
                            <input class="submit-button" type="submit" value="Login">
                            <br>
                            <br>
                        </form>
                        <br>
                        <a href="registration.phtml" class="regis-lnk">Creat New Account</a>
                     </center>
                </div>
                
        </div>
    </div>
    
</body>
</html>